services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports: 
      - "2181:2181"
    networks:
      - search-application-network
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5


  kafka:
    image: bitnami/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - search-application-network
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pranshubarar
    ports:
      - "3306:3306"
    networks:
      - search-application-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  connect:
    image: quay.io/debezium/connect:2.7
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      GROUP_ID: 1
      BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8083"
    depends_on:
      kafka: 
        condition: service_healthy
      mysql: 
        condition: service_healthy
    networks:
      - search-application-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports: 
      - "9200:9200"
    environment: 
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 30s
      retries: 20
      start_period: 30s 
 


    networks:
      - search-application-network

  crud_application:
    image: leegality/leegality-search-optimization-application
    ports: 
      - "8080:8080"
    networks:
      - search-application-network
    depends_on:
      mysql:
        condition: service_healthy

  kafka_consumer:
    image: kafka_consumer_for_search_optimization:0.0.1-SNAPSHOT
    environment:
       KAFKA_BOOTSTRAP_SERVER: kafka:9092
       ELASTIC_HOST: elasticsearch
       SPRING_ELASTICSEARCH_URIS: elasticsearch:9200
    networks:
      - search-application-network
    depends_on:
      elasticsearch:
        condition: service_healthy
      kafka:
        condition: service_healthy


networks:
  search-application-network:
    driver: bridge
  